//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ITNVPlayMsgManager.TelService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TelephonyServiceSoapBinding", Namespace="http://xml.avaya.com/ws/TelephonyService/2005/04/04")]
    public partial class TelephonyServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private @string sessionIDField;
        
        private System.Threading.SendOrPostCallback releaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback attachOperationCompleted;
        
        private System.Threading.SendOrPostCallback makeCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback disconnectActiveCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback singleStepTransferCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback singleStepConferenceCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback answerAlertingCallOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TelephonyServiceService() {
            this.Url = global::ITNVPlayMsgManager.Properties.Settings.Default.ITNVPlayMsgManager_TelService_TelephonyServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public @string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event releaseCompletedEventHandler releaseCompleted;
        
        /// <remarks/>
        public event attachCompletedEventHandler attachCompleted;
        
        /// <remarks/>
        public event makeCallCompletedEventHandler makeCallCompleted;
        
        /// <remarks/>
        public event disconnectActiveCallCompletedEventHandler disconnectActiveCallCompleted;
        
        /// <remarks/>
        public event singleStepTransferCallCompletedEventHandler singleStepTransferCallCompleted;
        
        /// <remarks/>
        public event singleStepConferenceCallCompletedEventHandler singleStepConferenceCallCompleted;
        
        /// <remarks/>
        public event answerAlertingCallCompletedEventHandler answerAlertingCallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("sessionID", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("releaseResponse", Namespace="http://TelephonyService.ws.avaya.com")]
        public empty release([System.Xml.Serialization.XmlElementAttribute("release", Namespace="http://TelephonyService.ws.avaya.com", IsNullable=true)] string release1) {
            object[] results = this.Invoke("release", new object[] {
                        release1});
            return ((empty)(results[0]));
        }
        
        /// <remarks/>
        public void releaseAsync(string release1) {
            this.releaseAsync(release1, null);
        }
        
        /// <remarks/>
        public void releaseAsync(string release1, object userState) {
            if ((this.releaseOperationCompleted == null)) {
                this.releaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreleaseOperationCompleted);
            }
            this.InvokeAsync("release", new object[] {
                        release1}, this.releaseOperationCompleted, userState);
        }
        
        private void OnreleaseOperationCompleted(object arg) {
            if ((this.releaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.releaseCompleted(this, new releaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("sessionID", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("attachResponse", Namespace="http://TelephonyService.ws.avaya.com")]
        public empty attach([System.Xml.Serialization.XmlElementAttribute("attach", Namespace="http://TelephonyService.ws.avaya.com", IsNullable=true)] string attach1) {
            object[] results = this.Invoke("attach", new object[] {
                        attach1});
            return ((empty)(results[0]));
        }
        
        /// <remarks/>
        public void attachAsync(string attach1) {
            this.attachAsync(attach1, null);
        }
        
        /// <remarks/>
        public void attachAsync(string attach1, object userState) {
            if ((this.attachOperationCompleted == null)) {
                this.attachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnattachOperationCompleted);
            }
            this.InvokeAsync("attach", new object[] {
                        attach1}, this.attachOperationCompleted, userState);
        }
        
        private void OnattachOperationCompleted(object arg) {
            if ((this.attachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.attachCompleted(this, new attachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("sessionID", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("makeCallResponse", Namespace="http://TelephonyService.ws.avaya.com")]
        public empty makeCall([System.Xml.Serialization.XmlElementAttribute("makeCall", Namespace="http://TelephonyService.ws.avaya.com")] endpoints makeCall1) {
            object[] results = this.Invoke("makeCall", new object[] {
                        makeCall1});
            return ((empty)(results[0]));
        }
        
        /// <remarks/>
        public void makeCallAsync(endpoints makeCall1) {
            this.makeCallAsync(makeCall1, null);
        }
        
        /// <remarks/>
        public void makeCallAsync(endpoints makeCall1, object userState) {
            if ((this.makeCallOperationCompleted == null)) {
                this.makeCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmakeCallOperationCompleted);
            }
            this.InvokeAsync("makeCall", new object[] {
                        makeCall1}, this.makeCallOperationCompleted, userState);
        }
        
        private void OnmakeCallOperationCompleted(object arg) {
            if ((this.makeCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.makeCallCompleted(this, new makeCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("sessionID", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("disconnectActiveCallResponse", Namespace="http://TelephonyService.ws.avaya.com")]
        public empty disconnectActiveCall([System.Xml.Serialization.XmlElementAttribute("disconnectActiveCall", Namespace="http://TelephonyService.ws.avaya.com")] extension disconnectActiveCall1) {
            object[] results = this.Invoke("disconnectActiveCall", new object[] {
                        disconnectActiveCall1});
            return ((empty)(results[0]));
        }
        
        /// <remarks/>
        public void disconnectActiveCallAsync(extension disconnectActiveCall1) {
            this.disconnectActiveCallAsync(disconnectActiveCall1, null);
        }
        
        /// <remarks/>
        public void disconnectActiveCallAsync(extension disconnectActiveCall1, object userState) {
            if ((this.disconnectActiveCallOperationCompleted == null)) {
                this.disconnectActiveCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OndisconnectActiveCallOperationCompleted);
            }
            this.InvokeAsync("disconnectActiveCall", new object[] {
                        disconnectActiveCall1}, this.disconnectActiveCallOperationCompleted, userState);
        }
        
        private void OndisconnectActiveCallOperationCompleted(object arg) {
            if ((this.disconnectActiveCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.disconnectActiveCallCompleted(this, new disconnectActiveCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("sessionID", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("singleStepTransferCallResponse", Namespace="http://TelephonyService.ws.avaya.com")]
        public empty singleStepTransferCall([System.Xml.Serialization.XmlElementAttribute("singleStepTransferCall", Namespace="http://TelephonyService.ws.avaya.com")] endpoints singleStepTransferCall1) {
            object[] results = this.Invoke("singleStepTransferCall", new object[] {
                        singleStepTransferCall1});
            return ((empty)(results[0]));
        }
        
        /// <remarks/>
        public void singleStepTransferCallAsync(endpoints singleStepTransferCall1) {
            this.singleStepTransferCallAsync(singleStepTransferCall1, null);
        }
        
        /// <remarks/>
        public void singleStepTransferCallAsync(endpoints singleStepTransferCall1, object userState) {
            if ((this.singleStepTransferCallOperationCompleted == null)) {
                this.singleStepTransferCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsingleStepTransferCallOperationCompleted);
            }
            this.InvokeAsync("singleStepTransferCall", new object[] {
                        singleStepTransferCall1}, this.singleStepTransferCallOperationCompleted, userState);
        }
        
        private void OnsingleStepTransferCallOperationCompleted(object arg) {
            if ((this.singleStepTransferCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.singleStepTransferCallCompleted(this, new singleStepTransferCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("sessionID", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("singleStepConferenceCallResponse", Namespace="http://TelephonyService.ws.avaya.com")]
        public empty singleStepConferenceCall([System.Xml.Serialization.XmlElementAttribute("singleStepConferenceCall", Namespace="http://TelephonyService.ws.avaya.com")] endpoints singleStepConferenceCall1) {
            object[] results = this.Invoke("singleStepConferenceCall", new object[] {
                        singleStepConferenceCall1});
            return ((empty)(results[0]));
        }
        
        /// <remarks/>
        public void singleStepConferenceCallAsync(endpoints singleStepConferenceCall1) {
            this.singleStepConferenceCallAsync(singleStepConferenceCall1, null);
        }
        
        /// <remarks/>
        public void singleStepConferenceCallAsync(endpoints singleStepConferenceCall1, object userState) {
            if ((this.singleStepConferenceCallOperationCompleted == null)) {
                this.singleStepConferenceCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsingleStepConferenceCallOperationCompleted);
            }
            this.InvokeAsync("singleStepConferenceCall", new object[] {
                        singleStepConferenceCall1}, this.singleStepConferenceCallOperationCompleted, userState);
        }
        
        private void OnsingleStepConferenceCallOperationCompleted(object arg) {
            if ((this.singleStepConferenceCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.singleStepConferenceCallCompleted(this, new singleStepConferenceCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("sessionID", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("answerAlertingCallResponse", Namespace="http://TelephonyService.ws.avaya.com")]
        public empty answerAlertingCall([System.Xml.Serialization.XmlElementAttribute("answerAlertingCall", Namespace="http://TelephonyService.ws.avaya.com")] extension answerAlertingCall1) {
            object[] results = this.Invoke("answerAlertingCall", new object[] {
                        answerAlertingCall1});
            return ((empty)(results[0]));
        }
        
        /// <remarks/>
        public void answerAlertingCallAsync(extension answerAlertingCall1) {
            this.answerAlertingCallAsync(answerAlertingCall1, null);
        }
        
        /// <remarks/>
        public void answerAlertingCallAsync(extension answerAlertingCall1, object userState) {
            if ((this.answerAlertingCallOperationCompleted == null)) {
                this.answerAlertingCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnanswerAlertingCallOperationCompleted);
            }
            this.InvokeAsync("answerAlertingCall", new object[] {
                        answerAlertingCall1}, this.answerAlertingCallOperationCompleted, userState);
        }
        
        private void OnanswerAlertingCallOperationCompleted(object arg) {
            if ((this.answerAlertingCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.answerAlertingCallCompleted(this, new answerAlertingCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("sessionID", Namespace="http://xml.avaya.com/ws/session", IsNullable=false)]
    public partial class @string : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TelephonyService.ws.avaya.com")]
    public partial class empty {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TelephonyService.ws.avaya.com")]
    public partial class extension {
        
        private string extension1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extension1 {
            get {
                return this.extension1Field;
            }
            set {
                this.extension1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TelephonyService.ws.avaya.com")]
    public partial class endpoints {
        
        private string originatingExtensionField;
        
        private string destinationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string originatingExtension {
            get {
                return this.originatingExtensionField;
            }
            set {
                this.originatingExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destinationNumber {
            get {
                return this.destinationNumberField;
            }
            set {
                this.destinationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void releaseCompletedEventHandler(object sender, releaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class releaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal releaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void attachCompletedEventHandler(object sender, attachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class attachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal attachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void makeCallCompletedEventHandler(object sender, makeCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class makeCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal makeCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void disconnectActiveCallCompletedEventHandler(object sender, disconnectActiveCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class disconnectActiveCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal disconnectActiveCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void singleStepTransferCallCompletedEventHandler(object sender, singleStepTransferCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class singleStepTransferCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal singleStepTransferCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void singleStepConferenceCallCompletedEventHandler(object sender, singleStepConferenceCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class singleStepConferenceCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal singleStepConferenceCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void answerAlertingCallCompletedEventHandler(object sender, answerAlertingCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class answerAlertingCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal answerAlertingCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empty)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591